language: node_js
node_js:
  - "6"

addons:
  code_climate:
    repo_token: 45a8888c7996bfbf756fbce7c14ec120777bef4d370deffcf2ec15f68afb468b

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
